# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - '*'
    # - master
    # - releases/*
  paths:
    exclude:
    - README.md
    - CHANGELOG.md

jobs:
  - job: Windows
    pool:
      vmImage: 'windows-latest'
    steps:
    - powershell: Get-Module Pester | out-String  ; Get-Module Pester -ListAvailable | out-String
    - pwsh: Get-Module Pester | out-String  ; Get-Module Pester -ListAvailable | out-String
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          'Loaded'
          Get-Module Pester | out-String
          'Available'
          Get-Module Pester -ListAvailable | out-String
          Install-Module -Name Pester -Force -SkipPublisherCheck -MaximumVersion 4.99.99
          'Loaded'
          Get-Module Pester | out-String
          'Available'
          Get-Module Pester -ListAvailable | out-String